language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO="django>=1.3,<1.4"
    - DJANGO="django>=1.4,<1.5"
install:
    - pip install $DJANGO django-shop django-mptt django-treeadmin django-easytests
script:
    python runtests.py
notifications:
    email: false